spring:
  application:
    name: spring-cloud-demo
  config:
    import: optional:xuantong:application.yml
  cloud:
    xuantong:
      server-addresses: ["127.0.0.1:8090"]
      namespace: public
      group: DEFAULT_GROUP
      cluster-id: ${XUANTONG_CLUSTER_ID:}
      transport-generation: ${XUANTONG_TRANSPORT_GENERATION:0}
      transport-pool: tcp-default
      tenant: default
      access-token: ${XUANTONG_ACCESS_TOKEN:}
      application-name: ${spring.application.name}
      tls:
        enabled: ${XUANTONG_CLIENT_TLS_ENABLED:false}
        trust-store: ${XUANTONG_CLIENT_TLS_TRUST_STORE:}
        trust-store-type: ${XUANTONG_CLIENT_TLS_TRUST_STORE_TYPE:PKCS12}
        trust-store-password: ${XUANTONG_CLIENT_TLS_TRUST_STORE_PASSWORD:}
        key-store: ${XUANTONG_CLIENT_TLS_KEY_STORE:}
        key-store-type: ${XUANTONG_CLIENT_TLS_KEY_STORE_TYPE:PKCS12}
        key-store-password: ${XUANTONG_CLIENT_TLS_KEY_STORE_PASSWORD:}
        key-password: ${XUANTONG_CLIENT_TLS_KEY_PASSWORD:}
        hostname-verification: true
        reload-interval-ms: ${XUANTONG_CLIENT_TLS_RELOAD_INTERVAL_MS:30000}
      config:
        enabled: true
        state-group-id: ${XUANTONG_CONFIG_GROUP_ID:config-default}
      discovery:
        enabled: true
        register: true
        state-group-id: ${XUANTONG_REGISTRY_GROUP_ID:registry-default}
        heartbeat-interval: 10s
        metadata:
          version: 2.0.0

server:
  port: 8081
