package com.xuantong.core.model.proxy;

import com.easy.query.core.expression.parser.core.available.TableAvailable;
import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.proxy.core.EntitySQLContext;
import com.xuantong.core.model.ConfigLog;
import com.easy.query.core.proxy.columns.types.SQLLongTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLStringTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLUtilDateTypeColumn;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 * 如果出现属性冲突请使用@ProxyProperty进行重命名
 *
 * @author easy-query
 */
public class ConfigLogProxy extends AbstractProxyEntity<ConfigLogProxy, ConfigLog> {

    private static final Class<ConfigLog> entityClass = ConfigLog.class;

    public static final ConfigLogProxy TABLE = createTable().createEmpty();

    public static ConfigLogProxy createTable() {
        return new ConfigLogProxy();
    }

    public ConfigLogProxy() {
    }

    /**
     * {@link ConfigLog#getId}
     */
    public SQLLongTypeColumn<ConfigLogProxy> id() {
        return getLongTypeColumn("id");
    }

    /**
     * {@link ConfigLog#getConfigId}
     */
    public SQLLongTypeColumn<ConfigLogProxy> configId() {
        return getLongTypeColumn("configId");
    }

    /**
     * 配置ID
     * {@link ConfigLog#getOperation}
     */
    public SQLStringTypeColumn<ConfigLogProxy> operation() {
        return getStringTypeColumn("operation");
    }

    /**
     * 操作类型：CREATEUPDATEDELETE
     * {@link ConfigLog#getOldValue}
     */
    public SQLStringTypeColumn<ConfigLogProxy> oldValue() {
        return getStringTypeColumn("oldValue");
    }

    /**
     * 旧值
     * {@link ConfigLog#getNewValue}
     */
    public SQLStringTypeColumn<ConfigLogProxy> newValue() {
        return getStringTypeColumn("newValue");
    }

    /**
     * 新值
     * {@link ConfigLog#getOperator}
     */
    public SQLStringTypeColumn<ConfigLogProxy> operator() {
        return getStringTypeColumn("operator");
    }

    /**
     * 操作人
     * {@link ConfigLog#getOperateTime}
     */
    public SQLUtilDateTypeColumn<ConfigLogProxy> operateTime() {
        return getUtilDateTypeColumn("operateTime");
    }

    /**
     * 操作时间
     * {@link ConfigLog#getIpAddress}
     */
    public SQLStringTypeColumn<ConfigLogProxy> ipAddress() {
        return getStringTypeColumn("ipAddress");
    }


    @Override
    public Class<ConfigLog> getEntityClass() {
        return entityClass;
    }

    @Override
    public ConfigLogProxy createNew() {
        return createTable();
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public ConfigLogProxyFetcher FETCHER = new ConfigLogProxyFetcher(this, null, SQLSelectAsExpression.empty);


    public static class ConfigLogProxyFetcher extends AbstractFetcher<ConfigLogProxy, ConfigLog, ConfigLogProxyFetcher> {

        public ConfigLogProxyFetcher(ConfigLogProxy proxy, ConfigLogProxyFetcher prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * {@link ConfigLog#getId}
         */
        public ConfigLogProxyFetcher id() {
            return add(getProxy().id());
        }

        /**
         * {@link ConfigLog#getConfigId}
         */
        public ConfigLogProxyFetcher configId() {
            return add(getProxy().configId());
        }

        /**
         * 配置ID
         * {@link ConfigLog#getOperation}
         */
        public ConfigLogProxyFetcher operation() {
            return add(getProxy().operation());
        }

        /**
         * 操作类型：CREATEUPDATEDELETE
         * {@link ConfigLog#getOldValue}
         */
        public ConfigLogProxyFetcher oldValue() {
            return add(getProxy().oldValue());
        }

        /**
         * 旧值
         * {@link ConfigLog#getNewValue}
         */
        public ConfigLogProxyFetcher newValue() {
            return add(getProxy().newValue());
        }

        /**
         * 新值
         * {@link ConfigLog#getOperator}
         */
        public ConfigLogProxyFetcher operator() {
            return add(getProxy().operator());
        }

        /**
         * 操作人
         * {@link ConfigLog#getOperateTime}
         */
        public ConfigLogProxyFetcher operateTime() {
            return add(getProxy().operateTime());
        }

        /**
         * 操作时间
         * {@link ConfigLog#getIpAddress}
         */
        public ConfigLogProxyFetcher ipAddress() {
            return add(getProxy().ipAddress());
        }


        @Override
        protected ConfigLogProxyFetcher createFetcher(ConfigLogProxy cp, AbstractFetcher<ConfigLogProxy, ConfigLog, ConfigLogProxyFetcher> prev, SQLSelectAsExpression sqlSelectExpression) {
            return new ConfigLogProxyFetcher(cp, this, sqlSelectExpression);
        }
    }


    public static final class Fields {
        public static final String id = "id";
        public static final String configId = "configId";
        public static final String operation = "operation";
        public static final String oldValue = "oldValue";
        public static final String newValue = "newValue";
        public static final String operator = "operator";
        public static final String operateTime = "operateTime";
        public static final String ipAddress = "ipAddress";

        private Fields() {
        }
    }
}
