package com.nimbus.core.model.proxy;

import com.easy.query.core.expression.parser.core.available.TableAvailable;
import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.proxy.core.EntitySQLContext;
import com.nimbus.core.model.Environment;
import com.easy.query.core.proxy.columns.types.SQLStringTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLIntegerTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLBooleanTypeColumn;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 * 如果出现属性冲突请使用@ProxyProperty进行重命名
 *
 * @author easy-query
 */
public class EnvironmentProxy extends AbstractProxyEntity<EnvironmentProxy, Environment> {

    private static final Class<Environment> entityClass = Environment.class;

    public static final EnvironmentProxy TABLE = createTable().createEmpty();

    public static EnvironmentProxy createTable() {
        return new EnvironmentProxy();
    }

    public EnvironmentProxy() {
    }

    /**
     * {@link Environment#getCode}
     */
    public SQLStringTypeColumn<EnvironmentProxy> code() {
        return getStringTypeColumn("code");
    }

    /**
     * 环境代码：devtestprod等
     * {@link Environment#getName}
     */
    public SQLStringTypeColumn<EnvironmentProxy> name() {
        return getStringTypeColumn("name");
    }

    /**
     * 环境名称
     * {@link Environment#getDescription}
     */
    public SQLStringTypeColumn<EnvironmentProxy> description() {
        return getStringTypeColumn("description");
    }

    /**
     * 环境描述
     * {@link Environment#getOrder}
     */
    public SQLIntegerTypeColumn<EnvironmentProxy> order() {
        return getIntegerTypeColumn("order");
    }

    /**
     * 显示顺序
     * {@link Environment#getIsDefault}
     */
    public SQLBooleanTypeColumn<EnvironmentProxy> isDefault() {
        return getBooleanTypeColumn("isDefault");
    }


    @Override
    public Class<Environment> getEntityClass() {
        return entityClass;
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public EnvironmentProxyFetcher FETCHER = new EnvironmentProxyFetcher(this, null, SQLSelectAsExpression.empty);


    public static class EnvironmentProxyFetcher extends AbstractFetcher<EnvironmentProxy, Environment, EnvironmentProxyFetcher> {

        public EnvironmentProxyFetcher(EnvironmentProxy proxy, EnvironmentProxyFetcher prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * {@link Environment#getCode}
         */
        public EnvironmentProxyFetcher code() {
            return add(getProxy().code());
        }

        /**
         * 环境代码：devtestprod等
         * {@link Environment#getName}
         */
        public EnvironmentProxyFetcher name() {
            return add(getProxy().name());
        }

        /**
         * 环境名称
         * {@link Environment#getDescription}
         */
        public EnvironmentProxyFetcher description() {
            return add(getProxy().description());
        }

        /**
         * 环境描述
         * {@link Environment#getOrder}
         */
        public EnvironmentProxyFetcher order() {
            return add(getProxy().order());
        }

        /**
         * 显示顺序
         * {@link Environment#getIsDefault}
         */
        public EnvironmentProxyFetcher isDefault() {
            return add(getProxy().isDefault());
        }


        @Override
        protected EnvironmentProxyFetcher createFetcher(EnvironmentProxy cp, AbstractFetcher<EnvironmentProxy, Environment, EnvironmentProxyFetcher> prev, SQLSelectAsExpression sqlSelectExpression) {
            return new EnvironmentProxyFetcher(cp, this, sqlSelectExpression);
        }
    }


    public static final class Fields {
        public static final String code = "code";
        public static final String name = "name";
        public static final String description = "description";
        public static final String order = "order";
        public static final String isDefault = "isDefault";

        private Fields() {
        }
    }
}
