# Xuantong Admin 配置
server:
  port: 8088
  contextPath: /xuantong-admin
solon:
  env: dev
  app:
    name: xuantong-admin
    group: xuantong

  serialization.json:
    dateAsFormat: 'yyyy-MM-dd HH:mm:ss'
    dateAsTimeZone: 'GMT+8'
    dateAsTicks: false
    longAsString: false
    boolAsInt: false
    nullStringAsEmpty: true
    nullBoolAsFalse: true
    nullNumberAsZero: true
    nullArrayAsEmpty: true
    nullAsWriteable: true
    enumAsName: true