server.port: 8080
solon.app:
  name: 'demo-app'
  group: 'demo'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
solon.cloud:
  xuantong:
    server: '127.0.0.1:8088'
    namespace: social:dev;demo,advert
    config:
      load: demo.aaa.yml
solon:
  logging:
    appender:
      console:
        enable: true
        level: DEBUG