server.port: 8080
solon.app:
  name: 'demo-app'
  group: 'demo'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
solon.cloud:
  xuantong:
    server: '223.109.140.78:8088'
    namespace: social:prod;demo,advert
    config:
      load: demo.aaa.yml