server.port: 8080
solon.app:
  name: 'demo-app'
  group: 'DEFAULT_GROUP'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
solon.cloud:
  xuantong:
    server: 127.0.0.1:8088 # 多个地址用逗号分隔
    namespace: public
    token: ${XUANTONG_ACCESS_TOKEN:}
    config:
      load: demo.aaa.yml # 该 dataId 的内容可通过 @Inject 使用
    discovery:
      enable: true
      healthCheckInterval: 10s
solon:
  logging:
    appender:
      console:
        enable: true
        level: INFO
